name: Lint and Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-black

    - run: pip install black==21.8b0
    - run: python -m black --check .

  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

#    - uses: actions/cache@v2
#      id: ffmpeg-cache
#      with:
#        path: /opt/ff/
#        key: ${{ runner.os }}-ff
#
#    - name: Download FFmpeg
#      if: steps.ffmpeg-cache.outputs.cache-hit != 'true'
#      run: |
#        wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
#        mkdir -p /opt/ff
#        tar --strip-components=1 -xJvf ffmpeg-release-amd64-static.tar.xz -C /opt/ff
#
#    - name: Link FFmpeg to usr/bin
#      run: |
#        sudo ln -s /opt/ff/ffmpeg /usr/bin/ffmpeg
#        sudo ln -s /opt/ff/ffprobe /usr/bin/ffprobe
#
#    - uses: actions/cache@v2
#      with:
#        path: ${{ env.pythonLocation }}
#        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-test.txt') }}

    - name: Install PySide6 requirements
      run: sudo apt install libopengl0 -y

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade -r requirements.txt
        python -m pip install --upgrade -r requirements-test.txt

    - name: Run tests
      env:
        PYTEST_QT_API: pyside6
      run: pytest tests
